version: 2.0
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: ssh -t $SSHUSER@$SSHHOST "bash ~/ASW/paint-splat-advanced-software-engineering/paint-splat/.circleci/code_deploy.sh"
      - run:
          name: Print the Current Time
          command: date
